// Code generated from docs/professional-finance-field-catalog-baseline.md; DO NOT EDIT.
package profinance

var fieldCatalogCoreData = []fieldCatalogCore{
	{SourceFieldID: 0, FieldCode: "report_date", FieldNameCN: "返回报告期", FieldNameEN: "Report Date", Category: "meta"},
	{SourceFieldID: 1, FieldCode: "basic_earnings_per_share", FieldNameCN: "基本每股收益", FieldNameEN: "Basic Earnings per Share", Category: "per_share"},
	{SourceFieldID: 2, FieldCode: "basic_earnings_per_share_after_deducting_non_recurring_profit_and_loss", FieldNameCN: "扣除非经常性损益每股收益", FieldNameEN: "Basic Earnings per Share after Deducting Non-recurring Profit and Loss", Category: "per_share"},
	{SourceFieldID: 3, FieldCode: "undistributed_profit_per_share", FieldNameCN: "每股未分配利润", FieldNameEN: "Undistributed Profit per Share", Category: "per_share"},
	{SourceFieldID: 4, FieldCode: "book_value_per_share", FieldNameCN: "每股净资产", FieldNameEN: "Book Value per Share", Category: "per_share"},
	{SourceFieldID: 5, FieldCode: "capital_reserve_per_share", FieldNameCN: "每股资本公积金", FieldNameEN: "Capital Reserve per Share", Category: "per_share"},
	{SourceFieldID: 6, FieldCode: "roe", FieldNameCN: "净资产收益率", FieldNameEN: "Return on Equity", Category: "profitability"},
	{SourceFieldID: 7, FieldCode: "operating_cash_flow_per_share", FieldNameCN: "每股经营现金流量", FieldNameEN: "Operating Cash Flow per Share", Category: "per_share"},
	{SourceFieldID: 8, FieldCode: "cash_and_cash_equivalents", FieldNameCN: "货币资金", FieldNameEN: "Cash and Cash Equivalents", Category: "balance_sheet"},
	{SourceFieldID: 9, FieldCode: "trading_financial_assets", FieldNameCN: "交易性金融资产", FieldNameEN: "Trading Financial Assets", Category: "balance_sheet"},
	{SourceFieldID: 10, FieldCode: "notes_receivable", FieldNameCN: "应收票据", FieldNameEN: "Notes Receivable", Category: "balance_sheet"},
	{SourceFieldID: 11, FieldCode: "accounts_receivable", FieldNameCN: "应收账款", FieldNameEN: "Accounts Receivable", Category: "balance_sheet"},
	{SourceFieldID: 12, FieldCode: "prepayments", FieldNameCN: "预付款项", FieldNameEN: "Prepayments", Category: "balance_sheet"},
	{SourceFieldID: 13, FieldCode: "other_receivables", FieldNameCN: "其他应收款", FieldNameEN: "Other Receivables", Category: "balance_sheet"},
	{SourceFieldID: 14, FieldCode: "due_from_related_companies", FieldNameCN: "应收关联公司款", FieldNameEN: "Amounts Due from Related Companies", Category: "balance_sheet"},
	{SourceFieldID: 15, FieldCode: "interest_receivable", FieldNameCN: "应收利息", FieldNameEN: "Interest Receivable", Category: "balance_sheet"},
	{SourceFieldID: 16, FieldCode: "dividends_receivable", FieldNameCN: "应收股利", FieldNameEN: "Dividends Receivable", Category: "balance_sheet"},
	{SourceFieldID: 17, FieldCode: "inventories", FieldNameCN: "存货", FieldNameEN: "Inventories", Category: "balance_sheet"},
	{SourceFieldID: 18, FieldCode: "consumable_biological_assets", FieldNameCN: "其中：消耗性生物资产", FieldNameEN: "Consumable Biological Assets", Category: "balance_sheet"},
	{SourceFieldID: 19, FieldCode: "non_current_assets_due_within_one_year", FieldNameCN: "一年内到期的非流动资产", FieldNameEN: "Non-current Assets Due within One Year", Category: "balance_sheet"},
	{SourceFieldID: 20, FieldCode: "other_current_assets", FieldNameCN: "其他流动资产", FieldNameEN: "Other Current Assets", Category: "balance_sheet"},
	{SourceFieldID: 21, FieldCode: "total_current_assets", FieldNameCN: "流动资产合计", FieldNameEN: "Total Current Assets", Category: "balance_sheet"},
	{SourceFieldID: 22, FieldCode: "available_for_sale_financial_assets", FieldNameCN: "可供出售金融资产", FieldNameEN: "Available-for-sale Financial Assets", Category: "balance_sheet"},
	{SourceFieldID: 23, FieldCode: "held_to_maturity_investments", FieldNameCN: "持有至到期投资", FieldNameEN: "Held-to-maturity Investments", Category: "balance_sheet"},
	{SourceFieldID: 24, FieldCode: "long_term_receivables", FieldNameCN: "长期应收款", FieldNameEN: "Long-term Receivables", Category: "balance_sheet"},
	{SourceFieldID: 25, FieldCode: "long_term_equity_investments", FieldNameCN: "长期股权投资", FieldNameEN: "Long-term Equity Investments", Category: "balance_sheet"},
	{SourceFieldID: 26, FieldCode: "investment_properties", FieldNameCN: "投资性房地产", FieldNameEN: "Investment Properties", Category: "balance_sheet"},
	{SourceFieldID: 27, FieldCode: "fixed_assets", FieldNameCN: "固定资产", FieldNameEN: "Fixed Assets", Category: "balance_sheet"},
	{SourceFieldID: 28, FieldCode: "construction_in_progress", FieldNameCN: "在建工程", FieldNameEN: "Construction in Progress", Category: "balance_sheet"},
	{SourceFieldID: 29, FieldCode: "construction_materials", FieldNameCN: "工程物资", FieldNameEN: "Construction Materials", Category: "balance_sheet"},
	{SourceFieldID: 30, FieldCode: "fixed_assets_pending_disposal", FieldNameCN: "固定资产清理", FieldNameEN: "Fixed Assets Pending Disposal", Category: "balance_sheet"},
	{SourceFieldID: 31, FieldCode: "productive_biological_assets", FieldNameCN: "生产性生物资产", FieldNameEN: "Productive Biological Assets", Category: "balance_sheet"},
	{SourceFieldID: 32, FieldCode: "oil_and_gas_assets", FieldNameCN: "油气资产", FieldNameEN: "Oil and Gas Assets", Category: "balance_sheet"},
	{SourceFieldID: 33, FieldCode: "intangible_assets", FieldNameCN: "无形资产", FieldNameEN: "Intangible Assets", Category: "balance_sheet"},
	{SourceFieldID: 34, FieldCode: "development_expenditure", FieldNameCN: "开发支出", FieldNameEN: "Development Expenditure", Category: "balance_sheet"},
	{SourceFieldID: 35, FieldCode: "goodwill", FieldNameCN: "商誉", FieldNameEN: "Goodwill", Category: "balance_sheet"},
	{SourceFieldID: 36, FieldCode: "long_term_deferred_expenses", FieldNameCN: "长期待摊费用", FieldNameEN: "Long-term Deferred Expenses", Category: "balance_sheet"},
	{SourceFieldID: 37, FieldCode: "deferred_tax_assets", FieldNameCN: "递延所得税资产", FieldNameEN: "Deferred Tax Assets", Category: "balance_sheet"},
	{SourceFieldID: 38, FieldCode: "other_non_current_assets", FieldNameCN: "其他非流动资产", FieldNameEN: "Other Non-current Assets", Category: "balance_sheet"},
	{SourceFieldID: 39, FieldCode: "total_non_current_assets", FieldNameCN: "非流动资产合计", FieldNameEN: "Total Non-current Assets", Category: "balance_sheet"},
	{SourceFieldID: 40, FieldCode: "total_assets", FieldNameCN: "资产总计", FieldNameEN: "Total Assets", Category: "balance_sheet"},
	{SourceFieldID: 41, FieldCode: "short_term_borrowings", FieldNameCN: "短期借款", FieldNameEN: "Short-term Borrowings", Category: "balance_sheet"},
	{SourceFieldID: 42, FieldCode: "trading_financial_liabilities", FieldNameCN: "交易性金融负债", FieldNameEN: "Trading Financial Liabilities", Category: "balance_sheet"},
	{SourceFieldID: 43, FieldCode: "notes_payable", FieldNameCN: "应付票据", FieldNameEN: "Notes Payable", Category: "balance_sheet"},
	{SourceFieldID: 44, FieldCode: "accounts_payable", FieldNameCN: "应付账款", FieldNameEN: "Accounts Payable", Category: "balance_sheet"},
	{SourceFieldID: 45, FieldCode: "advances_from_customers", FieldNameCN: "预收款项", FieldNameEN: "Advances from Customers", Category: "balance_sheet"},
	{SourceFieldID: 46, FieldCode: "employee_compensation_payable", FieldNameCN: "应付职工薪酬", FieldNameEN: "Employee Compensation Payable", Category: "balance_sheet"},
	{SourceFieldID: 47, FieldCode: "taxes_payable", FieldNameCN: "应交税费", FieldNameEN: "Taxes Payable", Category: "balance_sheet"},
	{SourceFieldID: 48, FieldCode: "interest_payable", FieldNameCN: "应付利息", FieldNameEN: "Interest Payable", Category: "balance_sheet"},
	{SourceFieldID: 49, FieldCode: "dividends_payable", FieldNameCN: "应付股利", FieldNameEN: "Dividends Payable", Category: "balance_sheet"},
	{SourceFieldID: 50, FieldCode: "other_payables", FieldNameCN: "其他应付款", FieldNameEN: "Other Payables", Category: "balance_sheet"},
	{SourceFieldID: 51, FieldCode: "due_to_related_companies", FieldNameCN: "应付关联公司款", FieldNameEN: "Amounts Due to Related Companies", Category: "balance_sheet"},
	{SourceFieldID: 52, FieldCode: "non_current_liabilities_due_within_one_year", FieldNameCN: "一年内到期的非流动负债", FieldNameEN: "Non-current Liabilities Due within One Year", Category: "balance_sheet"},
	{SourceFieldID: 53, FieldCode: "other_current_liabilities", FieldNameCN: "其他流动负债", FieldNameEN: "Other Current Liabilities", Category: "balance_sheet"},
	{SourceFieldID: 54, FieldCode: "total_current_liabilities", FieldNameCN: "流动负债合计", FieldNameEN: "Total Current Liabilities", Category: "balance_sheet"},
	{SourceFieldID: 55, FieldCode: "long_term_borrowings", FieldNameCN: "长期借款", FieldNameEN: "Long-term Borrowings", Category: "balance_sheet"},
	{SourceFieldID: 56, FieldCode: "bonds_payable", FieldNameCN: "应付债券", FieldNameEN: "Bonds Payable", Category: "balance_sheet"},
	{SourceFieldID: 57, FieldCode: "long_term_payables", FieldNameCN: "长期应付款", FieldNameEN: "Long-term Payables", Category: "balance_sheet"},
	{SourceFieldID: 58, FieldCode: "special_payables", FieldNameCN: "专项应付款", FieldNameEN: "Special Payables", Category: "balance_sheet"},
	{SourceFieldID: 59, FieldCode: "provisions", FieldNameCN: "预计负债", FieldNameEN: "Provisions", Category: "balance_sheet"},
	{SourceFieldID: 60, FieldCode: "deferred_tax_liabilities", FieldNameCN: "递延所得税负债", FieldNameEN: "Deferred Tax Liabilities", Category: "balance_sheet"},
	{SourceFieldID: 61, FieldCode: "other_non_current_liabilities", FieldNameCN: "其他非流动负债", FieldNameEN: "Other Non-current Liabilities", Category: "balance_sheet"},
	{SourceFieldID: 62, FieldCode: "total_non_current_liabilities", FieldNameCN: "非流动负债合计", FieldNameEN: "Total Non-current Liabilities", Category: "balance_sheet"},
	{SourceFieldID: 63, FieldCode: "total_liabilities", FieldNameCN: "负债合计", FieldNameEN: "Total Liabilities", Category: "balance_sheet"},
	{SourceFieldID: 64, FieldCode: "share_capital", FieldNameCN: "实收资本（或股本）", FieldNameEN: "Share Capital", Category: "balance_sheet"},
	{SourceFieldID: 65, FieldCode: "capital_reserve", FieldNameCN: "资本公积", FieldNameEN: "Capital Reserve", Category: "balance_sheet"},
	{SourceFieldID: 66, FieldCode: "surplus_reserve", FieldNameCN: "盈余公积", FieldNameEN: "Surplus Reserve", Category: "balance_sheet"},
	{SourceFieldID: 67, FieldCode: "treasury_shares", FieldNameCN: "减：库存股", FieldNameEN: "Treasury Shares", Category: "balance_sheet"},
	{SourceFieldID: 68, FieldCode: "retained_earnings", FieldNameCN: "未分配利润", FieldNameEN: "Retained Earnings", Category: "balance_sheet"},
	{SourceFieldID: 69, FieldCode: "non_controlling_interests", FieldNameCN: "少数股东权益", FieldNameEN: "Non-controlling Interests", Category: "balance_sheet"},
	{SourceFieldID: 70, FieldCode: "foreign_currency_translation_differences", FieldNameCN: "外币报表折算价差", FieldNameEN: "Foreign Currency Translation Differences", Category: "balance_sheet"},
	{SourceFieldID: 71, FieldCode: "adjustments_to_income_from_abnormal_operations", FieldNameCN: "非正常经营项目收益调整", FieldNameEN: "Adjustments to Income from Abnormal Operations", Category: "balance_sheet"},
	{SourceFieldID: 72, FieldCode: "total_equity", FieldNameCN: "所有者权益（或股东权益）合计", FieldNameEN: "Total Equity", Category: "balance_sheet"},
	{SourceFieldID: 73, FieldCode: "total_liabilities_and_equity", FieldNameCN: "负债和所有者（或股东权益）合计", FieldNameEN: "Total Liabilities and Equity", Category: "balance_sheet"},
	{SourceFieldID: 74, FieldCode: "operating_revenue", FieldNameCN: "其中：营业收入", FieldNameEN: "Operating Revenue", Category: "income_statement"},
	{SourceFieldID: 75, FieldCode: "operating_costs", FieldNameCN: "其中：营业成本", FieldNameEN: "Operating Costs", Category: "income_statement"},
	{SourceFieldID: 76, FieldCode: "taxes_and_surcharges", FieldNameCN: "营业税金及附加", FieldNameEN: "Taxes and Surcharges", Category: "income_statement"},
	{SourceFieldID: 77, FieldCode: "selling_expenses", FieldNameCN: "销售费用", FieldNameEN: "Selling Expenses", Category: "income_statement"},
	{SourceFieldID: 78, FieldCode: "administrative_expenses", FieldNameCN: "管理费用", FieldNameEN: "Administrative Expenses", Category: "income_statement"},
	{SourceFieldID: 79, FieldCode: "exploration_expenses", FieldNameCN: "勘探费用", FieldNameEN: "Exploration Expenses", Category: "income_statement"},
	{SourceFieldID: 80, FieldCode: "finance_expenses", FieldNameCN: "财务费用", FieldNameEN: "Finance Expenses", Category: "income_statement"},
	{SourceFieldID: 81, FieldCode: "asset_impairment_losses", FieldNameCN: "资产减值损失", FieldNameEN: "Asset Impairment Losses", Category: "income_statement"},
	{SourceFieldID: 82, FieldCode: "net_gain_from_fair_value_changes", FieldNameCN: "加：公允价值变动净收益", FieldNameEN: "Net Gain from Fair Value Changes", Category: "income_statement"},
	{SourceFieldID: 83, FieldCode: "investment_income", FieldNameCN: "投资收益", FieldNameEN: "Investment Income", Category: "income_statement"},
	{SourceFieldID: 84, FieldCode: "investment_income_from_associates_and_joint_ventures", FieldNameCN: "其中：对联营企业和合营企业的投资收益", FieldNameEN: "Investment Income from Associates and Joint Ventures", Category: "income_statement"},
	{SourceFieldID: 85, FieldCode: "other_items_affecting_operating_profit", FieldNameCN: "影响营业利润的其他科目", FieldNameEN: "Other Items Affecting Operating Profit", Category: "income_statement"},
	{SourceFieldID: 86, FieldCode: "operating_profit", FieldNameCN: "三、营业利润", FieldNameEN: "Operating Profit", Category: "income_statement"},
	{SourceFieldID: 87, FieldCode: "subsidy_income", FieldNameCN: "加：补贴收入", FieldNameEN: "Subsidy Income", Category: "income_statement"},
	{SourceFieldID: 88, FieldCode: "non_operating_income", FieldNameCN: "营业外收入", FieldNameEN: "Non-operating Income", Category: "income_statement"},
	{SourceFieldID: 89, FieldCode: "non_operating_expenses", FieldNameCN: "减：营业外支出", FieldNameEN: "Non-operating Expenses", Category: "income_statement"},
	{SourceFieldID: 90, FieldCode: "net_loss_from_disposal_of_non_current_assets", FieldNameCN: "其中：非流动资产处置净损失", FieldNameEN: "Net Loss from Disposal of Non-current Assets", Category: "income_statement"},
	{SourceFieldID: 91, FieldCode: "other_items_affecting_total_profit", FieldNameCN: "加：影响利润总额的其他科目", FieldNameEN: "Other Items Affecting Total Profit", Category: "income_statement"},
	{SourceFieldID: 92, FieldCode: "total_profit", FieldNameCN: "四、利润总额", FieldNameEN: "Total Profit", Category: "income_statement"},
	{SourceFieldID: 93, FieldCode: "income_tax_expense", FieldNameCN: "减：所得税", FieldNameEN: "Income Tax Expense", Category: "income_statement"},
	{SourceFieldID: 94, FieldCode: "other_items_affecting_net_profit", FieldNameCN: "加：影响净利润的其他科目", FieldNameEN: "Other Items Affecting Net Profit", Category: "income_statement"},
	{SourceFieldID: 95, FieldCode: "net_profit", FieldNameCN: "五、净利润", FieldNameEN: "Net Profit", Category: "income_statement"},
	{SourceFieldID: 96, FieldCode: "net_profit_attributable_to_owners_of_parent", FieldNameCN: "归属于母公司所有者的净利润", FieldNameEN: "Net Profit Attributable to Owners of the Parent", Category: "income_statement"},
	{SourceFieldID: 97, FieldCode: "profit_attributable_to_non_controlling_interests", FieldNameCN: "少数股东损益", FieldNameEN: "Profit Attributable to Non-controlling Interests", Category: "income_statement"},
	{SourceFieldID: 98, FieldCode: "cash_received_from_sale_of_goods_and_rendering_of_services", FieldNameCN: "销售商品、提供劳务收到的现金", FieldNameEN: "Cash Received from Sale of Goods and Rendering of Services", Category: "cash_flow_statement"},
	{SourceFieldID: 99, FieldCode: "tax_refunds_received", FieldNameCN: "收到的税费返还", FieldNameEN: "Tax Refunds Received", Category: "cash_flow_statement"},
	{SourceFieldID: 100, FieldCode: "other_cash_received_relating_to_operating_activities", FieldNameCN: "收到其他与经营活动有关的现金", FieldNameEN: "Other Cash Received Relating to Operating Activities", Category: "cash_flow_statement"},
	{SourceFieldID: 101, FieldCode: "subtotal_of_cash_inflows_from_operating_activities", FieldNameCN: "经营活动现金流入小计", FieldNameEN: "Subtotal of Cash Inflows from Operating Activities", Category: "cash_flow_statement"},
	{SourceFieldID: 102, FieldCode: "cash_paid_for_goods_and_services", FieldNameCN: "购买商品、接受劳务支付的现金", FieldNameEN: "Cash Paid for Goods and Services", Category: "cash_flow_statement"},
	{SourceFieldID: 103, FieldCode: "cash_paid_to_and_for_employees", FieldNameCN: "支付给职工以及为职工支付的现金", FieldNameEN: "Cash Paid to and for Employees", Category: "cash_flow_statement"},
	{SourceFieldID: 104, FieldCode: "cash_paid_for_taxes", FieldNameCN: "支付的各项税费", FieldNameEN: "Cash Paid for Taxes", Category: "cash_flow_statement"},
	{SourceFieldID: 105, FieldCode: "other_cash_paid_relating_to_operating_activities", FieldNameCN: "支付其他与经营活动有关的现金", FieldNameEN: "Other Cash Paid Relating to Operating Activities", Category: "cash_flow_statement"},
	{SourceFieldID: 106, FieldCode: "subtotal_of_cash_outflows_from_operating_activities", FieldNameCN: "经营活动现金流出小计", FieldNameEN: "Subtotal of Cash Outflows from Operating Activities", Category: "cash_flow_statement"},
	{SourceFieldID: 107, FieldCode: "net_cash_flow_from_operating_activities", FieldNameCN: "经营活动产生的现金流量净额", FieldNameEN: "Net Cash Flow from Operating Activities", Category: "cash_flow_statement"},
	{SourceFieldID: 108, FieldCode: "cash_received_from_recovery_of_investments", FieldNameCN: "收回投资收到的现金", FieldNameEN: "Cash Received from Recovery of Investments", Category: "cash_flow_statement"},
	{SourceFieldID: 109, FieldCode: "cash_received_from_investment_income", FieldNameCN: "取得投资收益收到的现金", FieldNameEN: "Cash Received from Investment Income", Category: "cash_flow_statement"},
	{SourceFieldID: 110, FieldCode: "net_cash_received_from_disposal_of_fixed_assets_intangible_assets_and_other_long_term_assets", FieldNameCN: "处置固定资产、无形资产和其他长期资产收回的现金净额", FieldNameEN: "Net Cash Received from Disposal of Fixed Assets, Intangible Assets and Other Long-term Assets", Category: "cash_flow_statement"},
	{SourceFieldID: 111, FieldCode: "net_cash_received_from_disposal_of_subsidiaries_and_other_business_units", FieldNameCN: "处置子公司及其他营业单位收到的现金净额", FieldNameEN: "Net Cash Received from Disposal of Subsidiaries and Other Business Units", Category: "cash_flow_statement"},
	{SourceFieldID: 112, FieldCode: "other_cash_received_relating_to_investing_activities", FieldNameCN: "收到其他与投资活动有关的现金", FieldNameEN: "Other Cash Received Relating to Investing Activities", Category: "cash_flow_statement"},
	{SourceFieldID: 113, FieldCode: "subtotal_of_cash_inflows_from_investing_activities", FieldNameCN: "投资活动现金流入小计", FieldNameEN: "Subtotal of Cash Inflows from Investing Activities", Category: "cash_flow_statement"},
	{SourceFieldID: 114, FieldCode: "cash_paid_for_acquisition_of_fixed_assets_intangible_assets_and_other_long_term_assets", FieldNameCN: "购建固定资产、无形资产和其他长期资产支付的现金", FieldNameEN: "Cash Paid for Acquisition of Fixed Assets, Intangible Assets and Other Long-term Assets", Category: "cash_flow_statement"},
	{SourceFieldID: 115, FieldCode: "cash_paid_for_investments", FieldNameCN: "投资支付的现金", FieldNameEN: "Cash Paid for Investments", Category: "cash_flow_statement"},
	{SourceFieldID: 116, FieldCode: "net_cash_paid_for_acquisition_of_subsidiaries_and_other_business_units", FieldNameCN: "取得子公司及其他营业单位支付的现金净额", FieldNameEN: "Net Cash Paid for Acquisition of Subsidiaries and Other Business Units", Category: "cash_flow_statement"},
	{SourceFieldID: 117, FieldCode: "other_cash_paid_relating_to_investing_activities", FieldNameCN: "支付其他与投资活动有关的现金", FieldNameEN: "Other Cash Paid Relating to Investing Activities", Category: "cash_flow_statement"},
	{SourceFieldID: 118, FieldCode: "subtotal_of_cash_outflows_from_investing_activities", FieldNameCN: "投资活动现金流出小计", FieldNameEN: "Subtotal of Cash Outflows from Investing Activities", Category: "cash_flow_statement"},
	{SourceFieldID: 119, FieldCode: "net_cash_flow_from_investing_activities", FieldNameCN: "投资活动产生的现金流量净额", FieldNameEN: "Net Cash Flow from Investing Activities", Category: "cash_flow_statement"},
	{SourceFieldID: 120, FieldCode: "cash_received_from_capital_contributions", FieldNameCN: "吸收投资收到的现金", FieldNameEN: "Cash Received from Capital Contributions", Category: "cash_flow_statement"},
	{SourceFieldID: 121, FieldCode: "cash_received_from_borrowings", FieldNameCN: "取得借款收到的现金", FieldNameEN: "Cash Received from Borrowings", Category: "cash_flow_statement"},
	{SourceFieldID: 122, FieldCode: "other_cash_received_relating_to_financing_activities", FieldNameCN: "收到其他与筹资活动有关的现金", FieldNameEN: "Other Cash Received Relating to Financing Activities", Category: "cash_flow_statement"},
	{SourceFieldID: 123, FieldCode: "subtotal_of_cash_inflows_from_financing_activities", FieldNameCN: "筹资活动现金流入小计", FieldNameEN: "Subtotal of Cash Inflows from Financing Activities", Category: "cash_flow_statement"},
	{SourceFieldID: 124, FieldCode: "cash_paid_for_repayment_of_debt", FieldNameCN: "偿还债务支付的现金", FieldNameEN: "Cash Paid for Repayment of Debt", Category: "cash_flow_statement"},
	{SourceFieldID: 125, FieldCode: "cash_paid_for_dividends_profit_distribution_or_interest", FieldNameCN: "分配股利、利润或偿付利息支付的现金", FieldNameEN: "Cash Paid for Dividends, Profit Distribution or Interest", Category: "cash_flow_statement"},
	{SourceFieldID: 126, FieldCode: "other_cash_paid_relating_to_financing_activities", FieldNameCN: "支付其他与筹资活动有关的现金", FieldNameEN: "Other Cash Paid Relating to Financing Activities", Category: "cash_flow_statement"},
	{SourceFieldID: 127, FieldCode: "subtotal_of_cash_outflows_from_financing_activities", FieldNameCN: "筹资活动现金流出小计", FieldNameEN: "Subtotal of Cash Outflows from Financing Activities", Category: "cash_flow_statement"},
	{SourceFieldID: 128, FieldCode: "net_cash_flow_from_financing_activities", FieldNameCN: "筹资活动产生的现金流量净额", FieldNameEN: "Net Cash Flow from Financing Activities", Category: "cash_flow_statement"},
	{SourceFieldID: 129, FieldCode: "effect_of_exchange_rate_changes_on_cash", FieldNameCN: "四、汇率变动对现金的影响", FieldNameEN: "Effect of Exchange Rate Changes on Cash", Category: "cash_flow_statement"},
	{SourceFieldID: 130, FieldCode: "effect_of_other_reasons_on_cash", FieldNameCN: "四(2)、其他原因对现金的影响", FieldNameEN: "Effect of Other Reasons on Cash", Category: "cash_flow_statement"},
	{SourceFieldID: 131, FieldCode: "net_increase_in_cash_and_cash_equivalents", FieldNameCN: "五、现金及现金等价物净增加额", FieldNameEN: "Net Increase in Cash and Cash Equivalents", Category: "cash_flow_statement"},
	{SourceFieldID: 132, FieldCode: "opening_balance_of_cash_and_cash_equivalents", FieldNameCN: "期初现金及现金等价物余额", FieldNameEN: "Opening Balance of Cash and Cash Equivalents", Category: "cash_flow_statement"},
	{SourceFieldID: 133, FieldCode: "closing_balance_of_cash_and_cash_equivalents", FieldNameCN: "期末现金及现金等价物余额", FieldNameEN: "Closing Balance of Cash and Cash Equivalents", Category: "cash_flow_statement"},
	{SourceFieldID: 134, FieldCode: "net_profit_for_cash_flow_reconciliation", FieldNameCN: "净利润", FieldNameEN: "Net Profit for Cash Flow Reconciliation", Category: "cash_flow_statement"},
	{SourceFieldID: 135, FieldCode: "asset_impairment_provisions", FieldNameCN: "加：资产减值准备", FieldNameEN: "Asset Impairment Provisions", Category: "cash_flow_statement"},
	{SourceFieldID: 136, FieldCode: "depreciation_of_fixed_assets_depletion_of_oil_and_gas_assets_and_depreciation_of_productive_biological_assets", FieldNameCN: "固定资产折旧、油气资产折耗、生产性生物资产折旧", FieldNameEN: "Depreciation of Fixed Assets, Depletion of Oil and Gas Assets and Depreciation of Productive Biological Assets", Category: "cash_flow_statement"},
	{SourceFieldID: 137, FieldCode: "amortization_of_intangible_assets", FieldNameCN: "无形资产摊销", FieldNameEN: "Amortization of Intangible Assets", Category: "cash_flow_statement"},
	{SourceFieldID: 138, FieldCode: "amortization_of_long_term_deferred_expenses", FieldNameCN: "长期待摊费用摊销", FieldNameEN: "Amortization of Long-term Deferred Expenses", Category: "cash_flow_statement"},
	{SourceFieldID: 139, FieldCode: "loss_on_disposal_of_fixed_assets_intangible_assets_and_other_long_term_assets", FieldNameCN: "处置固定资产、无形资产和其他长期资产的损失", FieldNameEN: "Loss on Disposal of Fixed Assets, Intangible Assets and Other Long-term Assets", Category: "cash_flow_statement"},
	{SourceFieldID: 140, FieldCode: "loss_on_scrapping_of_fixed_assets", FieldNameCN: "固定资产报废损失", FieldNameEN: "Loss on Scrapping of Fixed Assets", Category: "cash_flow_statement"},
	{SourceFieldID: 141, FieldCode: "loss_from_fair_value_changes", FieldNameCN: "公允价值变动损失", FieldNameEN: "Loss from Fair Value Changes", Category: "cash_flow_statement"},
	{SourceFieldID: 142, FieldCode: "finance_expenses_for_cash_flow_reconciliation", FieldNameCN: "财务费用", FieldNameEN: "Finance Expenses for Cash Flow Reconciliation", Category: "cash_flow_statement"},
	{SourceFieldID: 143, FieldCode: "investment_losses", FieldNameCN: "投资损失", FieldNameEN: "Investment Losses", Category: "cash_flow_statement"},
	{SourceFieldID: 144, FieldCode: "decrease_in_deferred_tax_assets", FieldNameCN: "递延所得税资产减少", FieldNameEN: "Decrease in Deferred Tax Assets", Category: "cash_flow_statement"},
	{SourceFieldID: 145, FieldCode: "increase_in_deferred_tax_liabilities", FieldNameCN: "递延所得税负债增加", FieldNameEN: "Increase in Deferred Tax Liabilities", Category: "cash_flow_statement"},
	{SourceFieldID: 146, FieldCode: "decrease_in_inventories", FieldNameCN: "存货的减少", FieldNameEN: "Decrease in Inventories", Category: "cash_flow_statement"},
	{SourceFieldID: 147, FieldCode: "decrease_in_operating_receivables", FieldNameCN: "经营性应收项目的减少", FieldNameEN: "Decrease in Operating Receivables", Category: "cash_flow_statement"},
	{SourceFieldID: 148, FieldCode: "increase_in_operating_payables", FieldNameCN: "经营性应付项目的增加", FieldNameEN: "Increase in Operating Payables", Category: "cash_flow_statement"},
	{SourceFieldID: 149, FieldCode: "other_cash_flow_reconciliation_items", FieldNameCN: "其他", FieldNameEN: "Other Cash Flow Reconciliation Items", Category: "cash_flow_statement"},
	{SourceFieldID: 150, FieldCode: "net_cash_flow_from_operating_activities_indirect_method", FieldNameCN: "经营活动产生的现金流量净额2", FieldNameEN: "Net Cash Flow from Operating Activities under the Indirect Method", Category: "cash_flow_statement"},
	{SourceFieldID: 151, FieldCode: "debt_converted_into_capital", FieldNameCN: "债务转为资本", FieldNameEN: "Debt Converted into Capital", Category: "cash_flow_statement"},
	{SourceFieldID: 152, FieldCode: "convertible_bonds_due_within_one_year", FieldNameCN: "一年内到期的可转换公司债券", FieldNameEN: "Convertible Bonds Due within One Year", Category: "cash_flow_statement"},
	{SourceFieldID: 153, FieldCode: "fixed_assets_acquired_under_finance_leases", FieldNameCN: "融资租入固定资产", FieldNameEN: "Fixed Assets Acquired under Finance Leases", Category: "cash_flow_statement"},
	{SourceFieldID: 154, FieldCode: "closing_cash_balance", FieldNameCN: "现金的期末余额", FieldNameEN: "Closing Cash Balance", Category: "cash_flow_statement"},
	{SourceFieldID: 155, FieldCode: "opening_cash_balance", FieldNameCN: "减：现金的期初余额", FieldNameEN: "Opening Cash Balance", Category: "cash_flow_statement"},
	{SourceFieldID: 156, FieldCode: "closing_cash_equivalents_balance", FieldNameCN: "加：现金等价物的期末余额", FieldNameEN: "Closing Cash Equivalents Balance", Category: "cash_flow_statement"},
	{SourceFieldID: 157, FieldCode: "opening_cash_equivalents_balance", FieldNameCN: "减：现金等价物的期初余额", FieldNameEN: "Opening Cash Equivalents Balance", Category: "cash_flow_statement"},
	{SourceFieldID: 158, FieldCode: "net_increase_in_cash_and_cash_equivalents_reconciliation", FieldNameCN: "现金及现金等价物净增加额", FieldNameEN: "Net Increase in Cash and Cash Equivalents from Reconciliation", Category: "cash_flow_statement"},
	{SourceFieldID: 159, FieldCode: "current_ratio", FieldNameCN: "流动比率(非金融类指标)", FieldNameEN: "Current Ratio", Category: "solvency"},
	{SourceFieldID: 160, FieldCode: "quick_ratio", FieldNameCN: "速动比率(非金融类指标)", FieldNameEN: "Quick Ratio", Category: "solvency"},
	{SourceFieldID: 161, FieldCode: "cash_ratio", FieldNameCN: "现金比率(%)(非金融类指标)", FieldNameEN: "Cash Ratio", Category: "solvency"},
	{SourceFieldID: 162, FieldCode: "interest_coverage_ratio", FieldNameCN: "利息保障倍数(非金融类指标)", FieldNameEN: "Interest Coverage Ratio", Category: "solvency"},
	{SourceFieldID: 163, FieldCode: "non_current_liabilities_ratio", FieldNameCN: "非流动负债比率(%)(非金融类指标)", FieldNameEN: "Non-current Liabilities Ratio", Category: "solvency"},
	{SourceFieldID: 164, FieldCode: "current_liabilities_ratio", FieldNameCN: "流动负债比率(%)(非金融类指标)", FieldNameEN: "Current Liabilities Ratio", Category: "solvency"},
	{SourceFieldID: 165, FieldCode: "cash_to_maturing_debt_ratio", FieldNameCN: "现金到期债务比率(%)(非金融类指标)", FieldNameEN: "Cash to Maturing Debt Ratio", Category: "solvency"},
	{SourceFieldID: 166, FieldCode: "debt_to_tangible_net_worth_ratio", FieldNameCN: "有形资产净值债务率(%)", FieldNameEN: "Debt to Tangible Net Worth Ratio", Category: "solvency"},
	{SourceFieldID: 167, FieldCode: "equity_multiplier", FieldNameCN: "权益乘数(%)", FieldNameEN: "Equity Multiplier", Category: "solvency"},
	{SourceFieldID: 168, FieldCode: "equity_to_total_liabilities_ratio", FieldNameCN: "股东的权益/负债合计(%)", FieldNameEN: "Equity to Total Liabilities Ratio", Category: "solvency"},
	{SourceFieldID: 169, FieldCode: "tangible_assets_to_total_liabilities_ratio", FieldNameCN: "有形资产/负债合计(%)", FieldNameEN: "Tangible Assets to Total Liabilities Ratio", Category: "solvency"},
	{SourceFieldID: 170, FieldCode: "net_cash_flow_from_operating_activities_to_total_liabilities_ratio", FieldNameCN: "经营活动产生的现金流量净额/负债合计(%)(非金融类指标)", FieldNameEN: "Net Cash Flow from Operating Activities to Total Liabilities Ratio", Category: "solvency"},
	{SourceFieldID: 171, FieldCode: "ebitda_to_total_liabilities_ratio", FieldNameCN: "EBITDA/负债合计(%)(非金融类指标)", FieldNameEN: "EBITDA to Total Liabilities Ratio", Category: "solvency"},
	{SourceFieldID: 172, FieldCode: "accounts_receivable_turnover_ratio", FieldNameCN: "应收帐款周转率(非金融类指标)", FieldNameEN: "Accounts Receivable Turnover Ratio", Category: "operating_efficiency"},
	{SourceFieldID: 173, FieldCode: "inventory_turnover_ratio", FieldNameCN: "存货周转率(非金融类指标)", FieldNameEN: "Inventory Turnover Ratio", Category: "operating_efficiency"},
	{SourceFieldID: 174, FieldCode: "working_capital_turnover_ratio", FieldNameCN: "运营资金周转率(非金融类指标)", FieldNameEN: "Working Capital Turnover Ratio", Category: "operating_efficiency"},
	{SourceFieldID: 175, FieldCode: "total_asset_turnover_ratio", FieldNameCN: "总资产周转率(非金融类指标)", FieldNameEN: "Total Asset Turnover Ratio", Category: "operating_efficiency"},
	{SourceFieldID: 176, FieldCode: "fixed_asset_turnover_ratio", FieldNameCN: "固定资产周转率(非金融类指标)", FieldNameEN: "Fixed Asset Turnover Ratio", Category: "operating_efficiency"},
	{SourceFieldID: 177, FieldCode: "accounts_receivable_turnover_days", FieldNameCN: "应收帐款周转天数(非金融类指标)", FieldNameEN: "Accounts Receivable Turnover Days", Category: "operating_efficiency"},
	{SourceFieldID: 178, FieldCode: "inventory_turnover_days", FieldNameCN: "存货周转天数(非金融类指标)", FieldNameEN: "Inventory Turnover Days", Category: "operating_efficiency"},
	{SourceFieldID: 179, FieldCode: "current_asset_turnover_ratio", FieldNameCN: "流动资产周转率(非金融类指标)", FieldNameEN: "Current Asset Turnover Ratio", Category: "operating_efficiency"},
	{SourceFieldID: 180, FieldCode: "current_asset_turnover_days", FieldNameCN: "流动资产周转天数(非金融类指标)", FieldNameEN: "Current Asset Turnover Days", Category: "operating_efficiency"},
	{SourceFieldID: 181, FieldCode: "total_asset_turnover_days", FieldNameCN: "总资产周转天数(非金融类指标)", FieldNameEN: "Total Asset Turnover Days", Category: "operating_efficiency"},
	{SourceFieldID: 182, FieldCode: "equity_turnover_ratio", FieldNameCN: "股东权益周转率(非金融类指标)", FieldNameEN: "Equity Turnover Ratio", Category: "operating_efficiency"},
	{SourceFieldID: 183, FieldCode: "operating_revenue_growth_rate", FieldNameCN: "营业收入增长率(%)", FieldNameEN: "Operating Revenue Growth Rate", Category: "growth"},
	{SourceFieldID: 184, FieldCode: "net_profit_growth_rate", FieldNameCN: "净利润增长率(%)", FieldNameEN: "Net Profit Growth Rate", Category: "growth"},
	{SourceFieldID: 185, FieldCode: "net_asset_growth_rate", FieldNameCN: "净资产增长率(%)", FieldNameEN: "Net Asset Growth Rate", Category: "growth"},
	{SourceFieldID: 186, FieldCode: "fixed_asset_growth_rate", FieldNameCN: "固定资产增长率(%)", FieldNameEN: "Fixed Asset Growth Rate", Category: "growth"},
	{SourceFieldID: 187, FieldCode: "total_asset_growth_rate", FieldNameCN: "总资产增长率(%)", FieldNameEN: "Total Asset Growth Rate", Category: "growth"},
	{SourceFieldID: 188, FieldCode: "investment_income_growth_rate", FieldNameCN: "投资收益增长率(%)", FieldNameEN: "Investment Income Growth Rate", Category: "growth"},
	{SourceFieldID: 189, FieldCode: "operating_profit_growth_rate", FieldNameCN: "营业利润增长率(%)", FieldNameEN: "Operating Profit Growth Rate", Category: "growth"},
	{SourceFieldID: 190, FieldCode: "basic_earnings_per_share_after_deducting_non_recurring_profit_and_loss_growth_rate", FieldNameCN: "扣非每股收益同比(%)", FieldNameEN: "Growth Rate of Basic Earnings per Share after Deducting Non-recurring Profit and Loss", Category: "growth"},
	{SourceFieldID: 191, FieldCode: "net_profit_after_deducting_non_recurring_profit_and_loss_growth_rate", FieldNameCN: "扣非净利润同比(%)", FieldNameEN: "Growth Rate of Net Profit after Deducting Non-recurring Profit and Loss", Category: "growth"},
	{SourceFieldID: 192, FieldCode: "reserved_growth_metric_192", FieldNameCN: "暂无", FieldNameEN: "Reserved Growth Metric 192", Category: "growth"},
	{SourceFieldID: 193, FieldCode: "profit_to_cost_and_expense_ratio", FieldNameCN: "成本费用利润率(%)", FieldNameEN: "Profit to Cost and Expense Ratio", Category: "profitability"},
	{SourceFieldID: 194, FieldCode: "operating_profit_margin", FieldNameCN: "营业利润率(非金融类指标)", FieldNameEN: "Operating Profit Margin", Category: "profitability"},
	{SourceFieldID: 195, FieldCode: "taxes_and_surcharges_ratio", FieldNameCN: "营业税金率(非金融类指标)", FieldNameEN: "Taxes and Surcharges Ratio", Category: "profitability"},
	{SourceFieldID: 196, FieldCode: "operating_cost_ratio", FieldNameCN: "营业成本率(非金融类指标)", FieldNameEN: "Operating Cost Ratio", Category: "profitability"},
	{SourceFieldID: 197, FieldCode: "roe_profitability", FieldNameCN: "净资产收益率", FieldNameEN: "Return on Equity (Profitability Variant)", Category: "profitability"},
	{SourceFieldID: 198, FieldCode: "return_on_investment", FieldNameCN: "投资收益率", FieldNameEN: "Return on Investment", Category: "profitability"},
	{SourceFieldID: 199, FieldCode: "sales_net_profit_margin", FieldNameCN: "销售净利率(%)", FieldNameEN: "Sales Net Profit Margin", Category: "profitability"},
	{SourceFieldID: 200, FieldCode: "return_on_total_assets", FieldNameCN: "总资产净利率", FieldNameEN: "Return on Total Assets", Category: "profitability"},
	{SourceFieldID: 201, FieldCode: "net_profit_margin", FieldNameCN: "净利润率(非金融类指标)", FieldNameEN: "Net Profit Margin", Category: "profitability"},
	{SourceFieldID: 202, FieldCode: "gross_profit_margin", FieldNameCN: "销售毛利率(%)(非金融类指标)", FieldNameEN: "Gross Profit Margin", Category: "profitability"},
	{SourceFieldID: 203, FieldCode: "selling_administrative_and_finance_expense_ratio", FieldNameCN: "三费比重(非金融类指标)", FieldNameEN: "Selling, Administrative and Finance Expense Ratio", Category: "profitability"},
	{SourceFieldID: 204, FieldCode: "administrative_expense_ratio", FieldNameCN: "管理费用率(非金融类指标)", FieldNameEN: "Administrative Expense Ratio", Category: "profitability"},
	{SourceFieldID: 205, FieldCode: "finance_expense_ratio", FieldNameCN: "财务费用率(非金融类指标)", FieldNameEN: "Finance Expense Ratio", Category: "profitability"},
	{SourceFieldID: 206, FieldCode: "net_profit_after_deducting_non_recurring_profit_and_loss", FieldNameCN: "扣除非经常性损益后的净利润", FieldNameEN: "Net Profit after Deducting Non-recurring Profit and Loss", Category: "profitability"},
	{SourceFieldID: 207, FieldCode: "ebit", FieldNameCN: "息税前利润(EBIT)", FieldNameEN: "Earnings Before Interest and Taxes", Category: "profitability"},
	{SourceFieldID: 208, FieldCode: "ebitda", FieldNameCN: "息税折旧摊销前利润(EBITDA)", FieldNameEN: "Earnings Before Interest, Taxes, Depreciation and Amortization", Category: "profitability"},
	{SourceFieldID: 209, FieldCode: "ebitda_to_total_operating_revenue_ratio", FieldNameCN: "EBITDA/营业总收入(%)(非金融类指标)", FieldNameEN: "EBITDA to Total Operating Revenue Ratio", Category: "profitability"},
	{SourceFieldID: 210, FieldCode: "debt_to_asset_ratio", FieldNameCN: "资产负债率(%)", FieldNameEN: "Debt-to-Asset Ratio", Category: "capital_structure"},
	{SourceFieldID: 211, FieldCode: "current_assets_to_total_assets_ratio", FieldNameCN: "流动资产比率(非金融类指标)", FieldNameEN: "Current Assets to Total Assets Ratio", Category: "capital_structure"},
	{SourceFieldID: 212, FieldCode: "cash_and_cash_equivalents_to_total_assets_ratio", FieldNameCN: "货币资金比率(非金融类指标)", FieldNameEN: "Cash and Cash Equivalents to Total Assets Ratio", Category: "capital_structure"},
	{SourceFieldID: 213, FieldCode: "inventory_to_total_assets_ratio", FieldNameCN: "存货比率(非金融类指标)", FieldNameEN: "Inventory to Total Assets Ratio", Category: "capital_structure"},
	{SourceFieldID: 214, FieldCode: "fixed_assets_to_total_assets_ratio", FieldNameCN: "固定资产比率", FieldNameEN: "Fixed Assets to Total Assets Ratio", Category: "capital_structure"},
	{SourceFieldID: 215, FieldCode: "long_term_liabilities_to_total_liabilities_ratio", FieldNameCN: "负债结构比(非金融类指标)", FieldNameEN: "Long-term Liabilities to Total Liabilities Ratio", Category: "capital_structure"},
	{SourceFieldID: 216, FieldCode: "equity_attributable_to_owners_of_parent_to_total_invested_capital_ratio", FieldNameCN: "归属于母公司股东权益/全部投入资本(%)", FieldNameEN: "Equity Attributable to Owners of the Parent to Total Invested Capital Ratio", Category: "capital_structure"},
	{SourceFieldID: 217, FieldCode: "equity_to_interest_bearing_debt_ratio", FieldNameCN: "股东的权益/带息债务(%)", FieldNameEN: "Equity to Interest-bearing Debt Ratio", Category: "capital_structure"},
	{SourceFieldID: 218, FieldCode: "tangible_assets_to_net_debt_ratio", FieldNameCN: "有形资产/净债务(%)", FieldNameEN: "Tangible Assets to Net Debt Ratio", Category: "capital_structure"},
	{SourceFieldID: 219, FieldCode: "operating_cash_flow_per_share_cash_flow_analysis", FieldNameCN: "每股经营性现金流(元)", FieldNameEN: "Operating Cash Flow per Share (Cash Flow Analysis Variant)", Category: "cash_flow_analysis"},
	{SourceFieldID: 220, FieldCode: "cash_content_of_operating_revenue", FieldNameCN: "营业收入现金含量(%)(非金融类指标)", FieldNameEN: "Cash Content of Operating Revenue", Category: "cash_flow_analysis"},
	{SourceFieldID: 221, FieldCode: "net_cash_flow_from_operating_activities_to_net_operating_income_ratio", FieldNameCN: "经营活动产生的现金流量净额/经营活动净收益(%)", FieldNameEN: "Net Cash Flow from Operating Activities to Net Operating Income Ratio", Category: "cash_flow_analysis"},
	{SourceFieldID: 222, FieldCode: "cash_received_from_goods_sales_and_services_to_operating_revenue_ratio", FieldNameCN: "销售商品提供劳务收到的现金/营业收入(%)", FieldNameEN: "Cash Received from Sale of Goods and Rendering of Services to Operating Revenue Ratio", Category: "cash_flow_analysis"},
	{SourceFieldID: 223, FieldCode: "net_cash_flow_from_operating_activities_to_operating_revenue_ratio", FieldNameCN: "经营活动产生的现金流量净额/营业收入", FieldNameEN: "Net Cash Flow from Operating Activities to Operating Revenue Ratio", Category: "cash_flow_analysis"},
	{SourceFieldID: 224, FieldCode: "capital_expenditure_to_depreciation_and_amortization_ratio", FieldNameCN: "资本支出/折旧和摊销", FieldNameEN: "Capital Expenditure to Depreciation and Amortization Ratio", Category: "cash_flow_analysis"},
	{SourceFieldID: 225, FieldCode: "net_increase_in_cash_and_cash_equivalents_per_share", FieldNameCN: "每股现金流量净额(元)", FieldNameEN: "Net Increase in Cash and Cash Equivalents per Share", Category: "cash_flow_analysis"},
	{SourceFieldID: 226, FieldCode: "net_cash_flow_from_operating_activities_to_short_term_debt_ratio", FieldNameCN: "经营净现金比率（短期债务）(非金融类指标)", FieldNameEN: "Net Cash Flow from Operating Activities to Short-term Debt Ratio", Category: "cash_flow_analysis"},
	{SourceFieldID: 227, FieldCode: "net_cash_flow_from_operating_activities_to_total_debt_ratio", FieldNameCN: "经营净现金比率（全部债务）", FieldNameEN: "Net Cash Flow from Operating Activities to Total Debt Ratio", Category: "cash_flow_analysis"},
	{SourceFieldID: 228, FieldCode: "net_cash_flow_from_operating_activities_to_net_profit_ratio", FieldNameCN: "经营活动现金净流量与净利润比率", FieldNameEN: "Net Cash Flow from Operating Activities to Net Profit Ratio", Category: "cash_flow_analysis"},
	{SourceFieldID: 229, FieldCode: "cash_recovery_ratio_of_total_assets", FieldNameCN: "全部资产现金回收率", FieldNameEN: "Cash Recovery Ratio of Total Assets", Category: "cash_flow_analysis"},
	{SourceFieldID: 230, FieldCode: "operating_revenue_single_quarter", FieldNameCN: "营业收入", FieldNameEN: "Single-quarter Operating Revenue", Category: "single_quarter"},
	{SourceFieldID: 231, FieldCode: "operating_profit_single_quarter", FieldNameCN: "营业利润", FieldNameEN: "Single-quarter Operating Profit", Category: "single_quarter"},
	{SourceFieldID: 232, FieldCode: "net_profit_attributable_to_owners_of_parent_single_quarter", FieldNameCN: "归属于母公司所有者的净利润", FieldNameEN: "Single-quarter Net Profit Attributable to Owners of the Parent", Category: "single_quarter"},
	{SourceFieldID: 233, FieldCode: "net_profit_after_deducting_non_recurring_profit_and_loss_single_quarter", FieldNameCN: "扣除非经常性损益后的净利润", FieldNameEN: "Single-quarter Net Profit after Deducting Non-recurring Profit and Loss", Category: "single_quarter"},
	{SourceFieldID: 234, FieldCode: "net_cash_flow_from_operating_activities_single_quarter", FieldNameCN: "经营活动产生的现金流量净额", FieldNameEN: "Single-quarter Net Cash Flow from Operating Activities", Category: "single_quarter"},
	{SourceFieldID: 235, FieldCode: "net_cash_flow_from_investing_activities_single_quarter", FieldNameCN: "投资活动产生的现金流量净额", FieldNameEN: "Single-quarter Net Cash Flow from Investing Activities", Category: "single_quarter"},
	{SourceFieldID: 236, FieldCode: "net_cash_flow_from_financing_activities_single_quarter", FieldNameCN: "筹资活动产生的现金流量净额", FieldNameEN: "Single-quarter Net Cash Flow from Financing Activities", Category: "single_quarter"},
	{SourceFieldID: 237, FieldCode: "net_increase_in_cash_and_cash_equivalents_single_quarter", FieldNameCN: "现金及现金等价物净增加额", FieldNameEN: "Single-quarter Net Increase in Cash and Cash Equivalents", Category: "single_quarter"},
	{SourceFieldID: 238, FieldCode: "total_shares", FieldNameCN: "总股本", FieldNameEN: "Total Shares", Category: "shareholder"},
	{SourceFieldID: 239, FieldCode: "float_a_shares", FieldNameCN: "已上市流通A股", FieldNameEN: "Float A Shares", Category: "shareholder"},
	{SourceFieldID: 240, FieldCode: "float_b_shares", FieldNameCN: "已上市流通B股", FieldNameEN: "Float B Shares", Category: "shareholder"},
	{SourceFieldID: 241, FieldCode: "float_h_shares", FieldNameCN: "已上市流通H股", FieldNameEN: "Float H Shares", Category: "shareholder"},
	{SourceFieldID: 242, FieldCode: "shareholder_count", FieldNameCN: "股东人数(户)", FieldNameEN: "Number of Shareholders", Category: "shareholder"},
	{SourceFieldID: 243, FieldCode: "largest_shareholder_shares_held", FieldNameCN: "第一大股东的持股数量", FieldNameEN: "Shares Held by the Largest Shareholder", Category: "shareholder"},
	{SourceFieldID: 244, FieldCode: "top_ten_float_shareholders_shares_held", FieldNameCN: "十大流通股东持股数量合计(股)", FieldNameEN: "Aggregate Shares Held by Top Ten Float Shareholders", Category: "shareholder"},
	{SourceFieldID: 245, FieldCode: "top_ten_shareholders_shares_held", FieldNameCN: "十大股东持股数量合计(股)", FieldNameEN: "Aggregate Shares Held by Top Ten Shareholders", Category: "shareholder"},
	{SourceFieldID: 246, FieldCode: "institution_count", FieldNameCN: "机构总量（家）", FieldNameEN: "Number of Institutional Holders", Category: "institutional_holding"},
	{SourceFieldID: 247, FieldCode: "institutional_shares_held", FieldNameCN: "机构持股总量(股)", FieldNameEN: "Institutional Shares Held", Category: "institutional_holding"},
	{SourceFieldID: 248, FieldCode: "qfii_institution_count", FieldNameCN: "QFII机构数", FieldNameEN: "Number of QFII Institutions", Category: "institutional_holding"},
	{SourceFieldID: 249, FieldCode: "qfii_shares_held", FieldNameCN: "QFII持股量", FieldNameEN: "QFII Shares Held", Category: "institutional_holding"},
	{SourceFieldID: 250, FieldCode: "brokerage_institution_count", FieldNameCN: "券商机构数", FieldNameEN: "Number of Brokerage Institutions", Category: "institutional_holding"},
	{SourceFieldID: 251, FieldCode: "brokerage_shares_held", FieldNameCN: "券商持股量", FieldNameEN: "Brokerage Shares Held", Category: "institutional_holding"},
	{SourceFieldID: 252, FieldCode: "insurance_institution_count", FieldNameCN: "保险机构数", FieldNameEN: "Number of Insurance Institutions", Category: "institutional_holding"},
	{SourceFieldID: 253, FieldCode: "insurance_shares_held", FieldNameCN: "保险持股量", FieldNameEN: "Insurance Shares Held", Category: "institutional_holding"},
	{SourceFieldID: 254, FieldCode: "fund_institution_count", FieldNameCN: "基金机构数", FieldNameEN: "Number of Fund Institutions", Category: "institutional_holding"},
	{SourceFieldID: 255, FieldCode: "fund_shares_held", FieldNameCN: "基金持股量", FieldNameEN: "Fund Shares Held", Category: "institutional_holding"},
	{SourceFieldID: 256, FieldCode: "social_security_institution_count", FieldNameCN: "社保机构数", FieldNameEN: "Number of Social Security Institutions", Category: "institutional_holding"},
	{SourceFieldID: 257, FieldCode: "social_security_shares_held", FieldNameCN: "社保持股量", FieldNameEN: "Social Security Shares Held", Category: "institutional_holding"},
	{SourceFieldID: 258, FieldCode: "private_fund_institution_count", FieldNameCN: "私募机构数", FieldNameEN: "Number of Private Fund Institutions", Category: "institutional_holding"},
	{SourceFieldID: 259, FieldCode: "private_fund_shares_held", FieldNameCN: "私募持股量", FieldNameEN: "Private Fund Shares Held", Category: "institutional_holding"},
	{SourceFieldID: 260, FieldCode: "finance_company_institution_count", FieldNameCN: "财务公司机构数", FieldNameEN: "Number of Finance Company Institutions", Category: "institutional_holding"},
	{SourceFieldID: 261, FieldCode: "finance_company_shares_held", FieldNameCN: "财务公司持股量", FieldNameEN: "Finance Company Shares Held", Category: "institutional_holding"},
	{SourceFieldID: 262, FieldCode: "annuity_institution_count", FieldNameCN: "年金机构数", FieldNameEN: "Number of Annuity Institutions", Category: "institutional_holding"},
	{SourceFieldID: 263, FieldCode: "annuity_shares_held", FieldNameCN: "年金持股量", FieldNameEN: "Annuity Shares Held", Category: "institutional_holding"},
	{SourceFieldID: 264, FieldCode: "top_ten_float_shareholders_a_shares_held", FieldNameCN: "十大流通股东中持有A股合计(股) [注：季度报告中，若股东同时持有非流通A股性质的股份(如同时持有流通A股和流通B股），指标264取的是包含同时持有非流通A股性质的流通股数]", FieldNameEN: "A Shares Held by Top Ten Float Shareholders", Category: "shareholder"},
	{SourceFieldID: 265, FieldCode: "largest_float_shareholder_shares_held", FieldNameCN: "第一大流通股东持股量(股)", FieldNameEN: "Shares Held by the Largest Float Shareholder", Category: "shareholder"},
	{SourceFieldID: 266, FieldCode: "free_float_shares", FieldNameCN: "自由流通股(股)[注：1.自由流通股=已流通A股-十大流通股东5%以上的A股；2.季度报告中，若股东同时持有非流通A股性质的股份(如同时持有流通A股和流通H股），5%以上的持股取的是不包含同时持有非流通A股性质的流通股数，结果可能偏大； 3.指标按报告期展示，新股在上市日的下个报告期才有数据]", FieldNameEN: "Free-float Shares", Category: "shareholder"},
	{SourceFieldID: 267, FieldCode: "restricted_tradable_a_shares", FieldNameCN: "受限流通A股(股)", FieldNameEN: "Restricted Tradable A Shares", Category: "shareholder"},
	{SourceFieldID: 268, FieldCode: "general_risk_reserve", FieldNameCN: "一般风险准备(金融类)", FieldNameEN: "General Risk Reserve", Category: "balance_sheet"},
	{SourceFieldID: 269, FieldCode: "other_comprehensive_income", FieldNameCN: "其他综合收益(利润表)", FieldNameEN: "Other Comprehensive Income", Category: "income_statement"},
	{SourceFieldID: 270, FieldCode: "total_comprehensive_income", FieldNameCN: "综合收益总额(利润表)", FieldNameEN: "Total Comprehensive Income", Category: "income_statement"},
	{SourceFieldID: 271, FieldCode: "equity_attributable_to_owners_of_parent", FieldNameCN: "归属于母公司股东权益(资产负债表)", FieldNameEN: "Equity Attributable to Owners of the Parent", Category: "balance_sheet"},
	{SourceFieldID: 272, FieldCode: "bank_institution_count", FieldNameCN: "银行机构数(家)(机构持股)", FieldNameEN: "Bank Institution Count", Category: "institutional_holding"},
	{SourceFieldID: 273, FieldCode: "bank_institution_shares_held", FieldNameCN: "银行持股量(股)(机构持股)", FieldNameEN: "Bank Institution Shares Held", Category: "institutional_holding"},
	{SourceFieldID: 274, FieldCode: "general_corporate_institution_count", FieldNameCN: "一般法人机构数(家)(机构持股)", FieldNameEN: "General Corporate Institution Count", Category: "institutional_holding"},
	{SourceFieldID: 275, FieldCode: "general_corporate_institution_shares_held", FieldNameCN: "一般法人持股量(股)(机构持股)", FieldNameEN: "General Corporate Institution Shares Held", Category: "institutional_holding"},
	{SourceFieldID: 276, FieldCode: "net_profit_ttm", FieldNameCN: "近一年净利润(元)", FieldNameEN: "Net Profit (TTM)", Category: "income_statement"},
	{SourceFieldID: 277, FieldCode: "trust_institution_count", FieldNameCN: "信托机构数(家)(机构持股)", FieldNameEN: "Trust Institution Count", Category: "institutional_holding"},
	{SourceFieldID: 278, FieldCode: "trust_institution_shares_held", FieldNameCN: "信托持股量(股)(机构持股)", FieldNameEN: "Trust Institution Shares Held", Category: "institutional_holding"},
	{SourceFieldID: 279, FieldCode: "special_corporate_institution_count", FieldNameCN: "特殊法人机构数(家)(机构持股)", FieldNameEN: "Special Corporate Institution Count", Category: "institutional_holding"},
	{SourceFieldID: 280, FieldCode: "special_corporate_institution_shares_held", FieldNameCN: "特殊法人持股量(股)(机构持股)", FieldNameEN: "Special Corporate Institution Shares Held", Category: "institutional_holding"},
	{SourceFieldID: 281, FieldCode: "weighted_roe", FieldNameCN: "加权净资产收益率(每股指标)", FieldNameEN: "Weighted Return on Equity", Category: "profitability"},
	{SourceFieldID: 282, FieldCode: "basic_earnings_per_share_after_deducting_non_recurring_profit_and_loss_single_quarter", FieldNameCN: "扣非每股收益(单季度财务指标)", FieldNameEN: "Basic Earnings per Share after Deducting Non-recurring Profit and Loss (Single Quarter)", Category: "single_quarter"},
	{SourceFieldID: 283, FieldCode: "operating_revenue_ttm", FieldNameCN: "最近一年营业收入（万元）", FieldNameEN: "Operating Revenue (TTM)", Category: "income_statement"},
	{SourceFieldID: 284, FieldCode: "state_backed_institution_shares_held", FieldNameCN: "国家队持股数量（万股)[注：本指标统计包含汇金公司、证金公司、外汇管理局旗下投资平台、国家队基金、国开、养老金以及中科汇通等国家队机构持股数量]", FieldNameEN: "Shares Held by State-backed Institutions", Category: "institutional_holding"},
	{SourceFieldID: 285, FieldCode: "earnings_preview_net_profit_yoy_growth_lower_bound", FieldNameCN: "业绩预告-本期净利润同比增幅下限%[注：指标285至294展示未来一个报告期的数据。例，3月31日至6月29日这段时间内展示的是中报的数据；如果最新的财务报告后面有多个报告期的业绩预告/快报，只能展示最新的财务报告后面的一个报告期的业绩预告/快报]", FieldNameEN: "Lower Bound of YoY Growth in Net Profit for Earnings Preview", Category: "earnings_preview"},
	{SourceFieldID: 286, FieldCode: "earnings_preview_net_profit_yoy_growth_upper_bound", FieldNameCN: "业绩预告-本期净利润同比增幅上限%", FieldNameEN: "Upper Bound of YoY Growth in Net Profit for Earnings Preview", Category: "earnings_preview"},
	{SourceFieldID: 287, FieldCode: "flash_report_net_profit_attributable_to_owners_of_parent", FieldNameCN: "业绩快报-归母净利润", FieldNameEN: "Net Profit Attributable to Owners of the Parent in Earnings Flash Report", Category: "earnings_flash_report"},
	{SourceFieldID: 288, FieldCode: "flash_report_net_profit_after_deducting_non_recurring_profit_and_loss", FieldNameCN: "业绩快报-扣非净利润", FieldNameEN: "Net Profit after Deducting Non-recurring Profit and Loss in Earnings Flash Report", Category: "earnings_flash_report"},
	{SourceFieldID: 289, FieldCode: "flash_report_total_assets", FieldNameCN: "业绩快报-总资产", FieldNameEN: "Total Assets in Earnings Flash Report", Category: "earnings_flash_report"},
	{SourceFieldID: 290, FieldCode: "flash_report_net_assets", FieldNameCN: "业绩快报-净资产", FieldNameEN: "Net Assets in Earnings Flash Report", Category: "earnings_flash_report"},
	{SourceFieldID: 291, FieldCode: "flash_report_earnings_per_share", FieldNameCN: "业绩快报-每股收益", FieldNameEN: "Earnings per Share in Earnings Flash Report", Category: "earnings_flash_report"},
	{SourceFieldID: 292, FieldCode: "flash_report_diluted_roe", FieldNameCN: "业绩快报-摊薄净资产收益率", FieldNameEN: "Diluted Return on Equity in Earnings Flash Report", Category: "earnings_flash_report"},
	{SourceFieldID: 293, FieldCode: "flash_report_weighted_roe", FieldNameCN: "业绩快报-加权净资产收益率", FieldNameEN: "Weighted Return on Equity in Earnings Flash Report", Category: "earnings_flash_report"},
	{SourceFieldID: 294, FieldCode: "flash_report_book_value_per_share", FieldNameCN: "业绩快报-每股净资产", FieldNameEN: "Book Value per Share in Earnings Flash Report", Category: "earnings_flash_report"},
	{SourceFieldID: 295, FieldCode: "notes_and_accounts_payable", FieldNameCN: "应付票据及应付账款(资产负债表)", FieldNameEN: "Notes and Accounts Payable", Category: "balance_sheet"},
	{SourceFieldID: 296, FieldCode: "notes_and_accounts_receivable", FieldNameCN: "应收票据及应收账款(资产负债表)", FieldNameEN: "Notes and Accounts Receivable", Category: "balance_sheet"},
	{SourceFieldID: 297, FieldCode: "non_current_deferred_income", FieldNameCN: "递延收益(资产负债表-非流动负债)", FieldNameEN: "Non-current Deferred Income", Category: "balance_sheet"},
	{SourceFieldID: 298, FieldCode: "other_comprehensive_income_in_equity", FieldNameCN: "其他综合收益(资产负债表)", FieldNameEN: "Other Comprehensive Income in Equity", Category: "balance_sheet"},
	{SourceFieldID: 299, FieldCode: "other_equity_instruments", FieldNameCN: "其他权益工具(资产负债表)", FieldNameEN: "Other Equity Instruments", Category: "balance_sheet"},
	{SourceFieldID: 300, FieldCode: "other_income", FieldNameCN: "其他收益(利润表)", FieldNameEN: "Other Income", Category: "income_statement"},
	{SourceFieldID: 301, FieldCode: "asset_disposal_income", FieldNameCN: "资产处置收益(利润表)", FieldNameEN: "Asset Disposal Income", Category: "income_statement"},
	{SourceFieldID: 302, FieldCode: "net_profit_from_continuing_operations", FieldNameCN: "持续经营净利润(利润表)", FieldNameEN: "Net Profit from Continuing Operations", Category: "income_statement"},
	{SourceFieldID: 303, FieldCode: "net_profit_from_discontinued_operations", FieldNameCN: "终止经营净利润(利润表)", FieldNameEN: "Net Profit from Discontinued Operations", Category: "income_statement"},
	{SourceFieldID: 304, FieldCode: "research_and_development_expenses", FieldNameCN: "研发费用(利润表)", FieldNameEN: "Research and Development Expenses", Category: "income_statement"},
	{SourceFieldID: 305, FieldCode: "interest_expense_in_finance_expenses", FieldNameCN: "其中:利息费用(利润表-财务费用)", FieldNameEN: "Interest Expense in Finance Expenses", Category: "income_statement"},
	{SourceFieldID: 306, FieldCode: "interest_income_in_finance_expenses", FieldNameCN: "其中:利息收入(利润表-财务费用)", FieldNameEN: "Interest Income in Finance Expenses", Category: "income_statement"},
	{SourceFieldID: 307, FieldCode: "net_cash_flow_from_operating_activities_ttm", FieldNameCN: "近一年经营活动现金流净额", FieldNameEN: "Net Cash Flow from Operating Activities (TTM)", Category: "cash_flow_statement"},
	{SourceFieldID: 308, FieldCode: "net_profit_attributable_to_owners_of_parent_ttm", FieldNameCN: "近一年归母净利润（万元）", FieldNameEN: "Net Profit Attributable to Owners of the Parent (TTM)", Category: "income_statement"},
	{SourceFieldID: 309, FieldCode: "net_profit_after_deducting_non_recurring_profit_and_loss_ttm", FieldNameCN: "近一年扣非净利润（万元）", FieldNameEN: "Net Profit after Deducting Non-recurring Profit and Loss (TTM)", Category: "income_statement"},
	{SourceFieldID: 310, FieldCode: "net_increase_in_cash_and_cash_equivalents_ttm", FieldNameCN: "近一年现金净流量（万元）", FieldNameEN: "Net Increase in Cash and Cash Equivalents (TTM)", Category: "cash_flow_statement"},
	{SourceFieldID: 311, FieldCode: "basic_earnings_per_share_single_quarter", FieldNameCN: "基本每股收益（单季度）", FieldNameEN: "Basic Earnings per Share (Single Quarter)", Category: "single_quarter"},
	{SourceFieldID: 312, FieldCode: "total_operating_revenue_single_quarter", FieldNameCN: "营业总收入(单季度)(万元)", FieldNameEN: "Total Operating Revenue (Single Quarter)", Category: "single_quarter"},
	{SourceFieldID: 313, FieldCode: "earnings_preview_announcement_date", FieldNameCN: "业绩预告公告日期 [注：本指标展示未来一个报告期的数据。例,3月31日至6月29日这段时间内展示的是中报的数据；如果最新的财务报告后面有多个报告期的业绩预告/快报，只能展示最新的财务报告后面的一个报告期的业绩预告/快报的数据；公告日期格式为YYMMDD，例：190101代表2019年1月1日]", FieldNameEN: "Earnings Preview Announcement Date", Category: "earnings_preview"},
	{SourceFieldID: 314, FieldCode: "financial_report_announcement_date", FieldNameCN: "财报公告日期 [注：日期格式为YYMMDD,例：190101代表2019年1月1日]", FieldNameEN: "Financial Report Announcement Date", Category: "disclosure"},
	{SourceFieldID: 315, FieldCode: "flash_report_announcement_date", FieldNameCN: "业绩快报公告日期 [注：本指标展示未来一个报告期的数据。例,3月31日至6月29日这段时间内展示的是中报的数据；如果最新的财务报告后面有多个报告期的业绩预告/快报，只能展示最新的财务报告后面的一个报告期的业绩预告/快报的数据；公告日期格式为YYMMDD，例：190101代表2019年1月1日]", FieldNameEN: "Earnings Flash Report Announcement Date", Category: "earnings_flash_report"},
	{SourceFieldID: 316, FieldCode: "net_cash_flow_from_investing_activities_ttm", FieldNameCN: "近一年投资活动现金流净额(万元)", FieldNameEN: "Net Cash Flow from Investing Activities (TTM)", Category: "cash_flow_statement"},
	{SourceFieldID: 317, FieldCode: "earnings_preview_net_profit_lower_bound", FieldNameCN: "业绩预告-本期净利润下限(万元)[注：指标317至318展示未来一个报告期的数据。例，3月31日至6月29日这段时间内展示的是中报的数据；如果最新的财务报告后面有多个报告期的业绩预告/快报，只能展示最新的财务报告后面的一个报告期的业绩预告/快报]", FieldNameEN: "Lower Bound of Net Profit for Earnings Preview", Category: "earnings_preview"},
	{SourceFieldID: 318, FieldCode: "earnings_preview_net_profit_upper_bound", FieldNameCN: "业绩预告-本期净利润上限(万元)", FieldNameEN: "Upper Bound of Net Profit for Earnings Preview", Category: "earnings_preview"},
	{SourceFieldID: 319, FieldCode: "total_operating_revenue_ttm", FieldNameCN: "营业总收入TTM(万元)", FieldNameEN: "Total Operating Revenue (TTM)", Category: "income_statement"},
	{SourceFieldID: 320, FieldCode: "employee_count", FieldNameCN: "员工总数(人)", FieldNameEN: "Employee Count", Category: "disclosure"},
	{SourceFieldID: 321, FieldCode: "free_cash_flow_to_firm_per_share", FieldNameCN: "每股企业自由现金流", FieldNameEN: "Free Cash Flow to Firm per Share", Category: "per_share"},
	{SourceFieldID: 322, FieldCode: "free_cash_flow_to_equity_per_share", FieldNameCN: "每股股东自由现金流", FieldNameEN: "Free Cash Flow to Equity per Share", Category: "per_share"},
	{SourceFieldID: 401, FieldCode: "special_reserve", FieldNameCN: "专项储备(万元)", FieldNameEN: "Special Reserve", Category: "balance_sheet"},
	{SourceFieldID: 402, FieldCode: "settlement_reserve_fund", FieldNameCN: "结算备付金(万元)", FieldNameEN: "Settlement Reserve Fund", Category: "balance_sheet"},
	{SourceFieldID: 403, FieldCode: "funds_lent", FieldNameCN: "拆出资金(万元)", FieldNameEN: "Funds Lent", Category: "balance_sheet"},
	{SourceFieldID: 404, FieldCode: "loans_and_advances_current", FieldNameCN: "发放贷款及垫款(万元)(流动资产科目)", FieldNameEN: "Loans and Advances under Current Assets", Category: "balance_sheet"},
	{SourceFieldID: 405, FieldCode: "derivative_financial_assets", FieldNameCN: "衍生金融资产(万元)", FieldNameEN: "Derivative Financial Assets", Category: "balance_sheet"},
	{SourceFieldID: 406, FieldCode: "premiums_receivable", FieldNameCN: "应收保费(万元)", FieldNameEN: "Premiums Receivable", Category: "balance_sheet"},
	{SourceFieldID: 407, FieldCode: "reinsurance_receivables", FieldNameCN: "应收分保账款(万元)", FieldNameEN: "Reinsurance Receivables", Category: "balance_sheet"},
	{SourceFieldID: 408, FieldCode: "reinsurance_contract_reserves_receivable", FieldNameCN: "应收分保合同准备金(万元)", FieldNameEN: "Reinsurance Contract Reserves Receivable", Category: "balance_sheet"},
	{SourceFieldID: 409, FieldCode: "financial_assets_purchased_under_resale_agreements", FieldNameCN: "买入返售金融资产(万元)", FieldNameEN: "Financial Assets Purchased under Resale Agreements", Category: "balance_sheet"},
	{SourceFieldID: 410, FieldCode: "assets_held_for_sale", FieldNameCN: "划分为持有待售的资产(万元)", FieldNameEN: "Assets Held for Sale", Category: "balance_sheet"},
	{SourceFieldID: 411, FieldCode: "loans_and_advances_non_current", FieldNameCN: "发放贷款及垫款(万元)(非流动资产科目)", FieldNameEN: "Loans and Advances under Non-current Assets", Category: "balance_sheet"},
	{SourceFieldID: 412, FieldCode: "borrowings_from_central_bank", FieldNameCN: "向中央银行借款(万元)", FieldNameEN: "Borrowings from Central Bank", Category: "balance_sheet"},
	{SourceFieldID: 413, FieldCode: "deposits_from_customers_and_interbank", FieldNameCN: "吸收存款及同业存放(万元)", FieldNameEN: "Deposits from Customers and Interbank", Category: "balance_sheet"},
	{SourceFieldID: 414, FieldCode: "funds_borrowed", FieldNameCN: "拆入资金(万元)", FieldNameEN: "Funds Borrowed", Category: "balance_sheet"},
	{SourceFieldID: 415, FieldCode: "derivative_financial_liabilities", FieldNameCN: "衍生金融负债(万元)", FieldNameEN: "Derivative Financial Liabilities", Category: "balance_sheet"},
	{SourceFieldID: 416, FieldCode: "financial_assets_sold_under_repurchase_agreements", FieldNameCN: "卖出回购金融资产款(万元)", FieldNameEN: "Financial Assets Sold under Repurchase Agreements", Category: "balance_sheet"},
	{SourceFieldID: 417, FieldCode: "fees_and_commissions_payable", FieldNameCN: "应付手续费及佣金(万元)", FieldNameEN: "Fees and Commissions Payable", Category: "balance_sheet"},
	{SourceFieldID: 418, FieldCode: "reinsurance_payables", FieldNameCN: "应付分保账款(万元)", FieldNameEN: "Reinsurance Payables", Category: "balance_sheet"},
	{SourceFieldID: 419, FieldCode: "insurance_contract_reserves", FieldNameCN: "保险合同准备金(万元)", FieldNameEN: "Insurance Contract Reserves", Category: "balance_sheet"},
	{SourceFieldID: 420, FieldCode: "funds_received_as_agent_of_stock_exchange", FieldNameCN: "代理买卖证券款(万元)", FieldNameEN: "Funds Received as Agent of Stock Exchange", Category: "balance_sheet"},
	{SourceFieldID: 421, FieldCode: "funds_received_as_securities_underwriter", FieldNameCN: "代理承销证券款(万元)", FieldNameEN: "Funds Received as Securities Underwriter", Category: "balance_sheet"},
	{SourceFieldID: 422, FieldCode: "liabilities_held_for_sale", FieldNameCN: "划分为持有待售的负债(万元)", FieldNameEN: "Liabilities Held for Sale", Category: "balance_sheet"},
	{SourceFieldID: 423, FieldCode: "provisions_extended_balance_sheet", FieldNameCN: "预计负债(万元)", FieldNameEN: "Provisions (Extended Balance Sheet Variant)", Category: "balance_sheet"},
	{SourceFieldID: 424, FieldCode: "deferred_income_current", FieldNameCN: "递延收益(万元)（流动负债科目，公告此科目的股票较少，大部分公司没有此数据）", FieldNameEN: "Deferred Income under Current Liabilities", Category: "balance_sheet"},
	{SourceFieldID: 425, FieldCode: "preferred_shares_non_current_liabilities", FieldNameCN: "其中:优先股(万元)(非流动负债科目)", FieldNameEN: "Preferred Shares under Non-current Liabilities", Category: "balance_sheet"},
	{SourceFieldID: 426, FieldCode: "perpetual_bonds_non_current_liabilities", FieldNameCN: "永续债(万元)(非流动负债科目)", FieldNameEN: "Perpetual Bonds under Non-current Liabilities", Category: "balance_sheet"},
	{SourceFieldID: 427, FieldCode: "long_term_employee_compensation_payable", FieldNameCN: "长期应付职工薪酬(万元)", FieldNameEN: "Long-term Employee Compensation Payable", Category: "balance_sheet"},
	{SourceFieldID: 428, FieldCode: "preferred_shares_equity", FieldNameCN: "其中:优先股(万元)(所有者权益科目)", FieldNameEN: "Preferred Shares under Equity", Category: "balance_sheet"},
	{SourceFieldID: 429, FieldCode: "perpetual_bonds_equity", FieldNameCN: "永续债(万元)(所有者权益科目)", FieldNameEN: "Perpetual Bonds under Equity", Category: "balance_sheet"},
	{SourceFieldID: 430, FieldCode: "debt_investments", FieldNameCN: "债权投资(万元)", FieldNameEN: "Debt Investments", Category: "balance_sheet"},
	{SourceFieldID: 431, FieldCode: "other_debt_investments", FieldNameCN: "其他债权投资(万元)", FieldNameEN: "Other Debt Investments", Category: "balance_sheet"},
	{SourceFieldID: 432, FieldCode: "other_equity_instrument_investments", FieldNameCN: "其他权益工具投资(万元)", FieldNameEN: "Other Equity Instrument Investments", Category: "balance_sheet"},
	{SourceFieldID: 433, FieldCode: "other_non_current_financial_assets", FieldNameCN: "其他非流动金融资产(万元)", FieldNameEN: "Other Non-current Financial Assets", Category: "balance_sheet"},
	{SourceFieldID: 434, FieldCode: "contract_liabilities", FieldNameCN: "合同负债(万元)", FieldNameEN: "Contract Liabilities", Category: "balance_sheet"},
	{SourceFieldID: 435, FieldCode: "contract_assets", FieldNameCN: "合同资产(万元)", FieldNameEN: "Contract Assets", Category: "balance_sheet"},
	{SourceFieldID: 436, FieldCode: "other_assets", FieldNameCN: "其他资产(万元)", FieldNameEN: "Other Assets", Category: "balance_sheet"},
	{SourceFieldID: 437, FieldCode: "receivables_financing", FieldNameCN: "应收款项融资(万元)", FieldNameEN: "Receivables Financing", Category: "balance_sheet"},
	{SourceFieldID: 438, FieldCode: "right_of_use_assets", FieldNameCN: "使用权资产(万元)", FieldNameEN: "Right-of-use Assets", Category: "balance_sheet"},
	{SourceFieldID: 439, FieldCode: "lease_liabilities", FieldNameCN: "租赁负债(万元)", FieldNameEN: "Lease Liabilities", Category: "balance_sheet"},
	{SourceFieldID: 501, FieldCode: "diluted_earnings_per_share", FieldNameCN: "稀释每股收益(元)", FieldNameEN: "Diluted Earnings per Share", Category: "income_statement"},
	{SourceFieldID: 502, FieldCode: "total_operating_revenue", FieldNameCN: "营业总收入(万元)", FieldNameEN: "Total Operating Revenue", Category: "income_statement"},
	{SourceFieldID: 503, FieldCode: "foreign_exchange_gains", FieldNameCN: "汇兑收益(万元)", FieldNameEN: "Foreign Exchange Gains", Category: "income_statement"},
	{SourceFieldID: 504, FieldCode: "comprehensive_income_attributable_to_owners_of_parent", FieldNameCN: "其中:归属于母公司综合收益(万元)", FieldNameEN: "Comprehensive Income Attributable to Owners of the Parent", Category: "income_statement"},
	{SourceFieldID: 505, FieldCode: "comprehensive_income_attributable_to_non_controlling_interests", FieldNameCN: "其中:归属于少数股东综合收益(万元)", FieldNameEN: "Comprehensive Income Attributable to Non-controlling Interests", Category: "income_statement"},
	{SourceFieldID: 506, FieldCode: "interest_income", FieldNameCN: "利息收入(万元)", FieldNameEN: "Interest Income", Category: "income_statement"},
	{SourceFieldID: 507, FieldCode: "earned_premiums", FieldNameCN: "已赚保费(万元)", FieldNameEN: "Earned Premiums", Category: "income_statement"},
	{SourceFieldID: 508, FieldCode: "fee_and_commission_income", FieldNameCN: "手续费及佣金收入(万元)", FieldNameEN: "Fee and Commission Income", Category: "income_statement"},
	{SourceFieldID: 509, FieldCode: "interest_expense", FieldNameCN: "利息支出(万元)", FieldNameEN: "Interest Expense", Category: "income_statement"},
	{SourceFieldID: 510, FieldCode: "fee_and_commission_expenses", FieldNameCN: "手续费及佣金支出(万元)", FieldNameEN: "Fee and Commission Expenses", Category: "income_statement"},
	{SourceFieldID: 511, FieldCode: "surrender_value", FieldNameCN: "退保金(万元)", FieldNameEN: "Surrender Value", Category: "income_statement"},
	{SourceFieldID: 512, FieldCode: "net_claims_incurred", FieldNameCN: "赔付支出净额(万元)", FieldNameEN: "Net Claims Incurred", Category: "income_statement"},
	{SourceFieldID: 513, FieldCode: "net_increase_in_insurance_contract_reserves", FieldNameCN: "提取保险合同准备金净额(万元)", FieldNameEN: "Net Increase in Insurance Contract Reserves", Category: "income_statement"},
	{SourceFieldID: 514, FieldCode: "policyholder_dividend_expenses", FieldNameCN: "保单红利支出(万元)", FieldNameEN: "Policyholder Dividend Expenses", Category: "income_statement"},
	{SourceFieldID: 515, FieldCode: "reinsurance_expenses", FieldNameCN: "分保费用(万元)", FieldNameEN: "Reinsurance Expenses", Category: "income_statement"},
	{SourceFieldID: 516, FieldCode: "gain_on_disposal_of_non_current_assets", FieldNameCN: "其中:非流动资产处置利得(万元)", FieldNameEN: "Gain on Disposal of Non-current Assets", Category: "income_statement"},
	{SourceFieldID: 517, FieldCode: "credit_impairment_losses", FieldNameCN: "信用减值损失(万元)", FieldNameEN: "Credit Impairment Losses", Category: "income_statement"},
	{SourceFieldID: 518, FieldCode: "net_exposure_hedging_gains", FieldNameCN: "净敞口套期收益(万元)", FieldNameEN: "Net Exposure Hedging Gains", Category: "income_statement"},
	{SourceFieldID: 519, FieldCode: "total_operating_costs", FieldNameCN: "营业总成本(万元)", FieldNameEN: "Total Operating Costs", Category: "income_statement"},
	{SourceFieldID: 520, FieldCode: "credit_impairment_losses_2019_format", FieldNameCN: "信用减值损失(万元、2019格式)", FieldNameEN: "Credit Impairment Losses, 2019 Format", Category: "income_statement"},
	{SourceFieldID: 521, FieldCode: "asset_impairment_losses_2019_format", FieldNameCN: "资产减值损失(万元、2019格式)", FieldNameEN: "Asset Impairment Losses, 2019 Format", Category: "income_statement"},
	{SourceFieldID: 561, FieldCode: "effect_of_other_reasons_on_cash_for_closing_cash_balance", FieldNameCN: "加:其他原因对现金的影响2(万元)(现金的期末余额科目)", FieldNameEN: "Effect of Other Reasons on Cash for Closing Cash Balance", Category: "cash_flow_statement"},
	{SourceFieldID: 562, FieldCode: "net_increase_in_customer_deposits_and_interbank_deposits", FieldNameCN: "客户存款和同业存放款项净增加额(万元)", FieldNameEN: "Net Increase in Customer Deposits and Interbank Deposits", Category: "cash_flow_statement"},
	{SourceFieldID: 563, FieldCode: "net_increase_in_borrowings_from_central_bank", FieldNameCN: "向中央银行借款净增加额(万元)", FieldNameEN: "Net Increase in Borrowings from the Central Bank", Category: "cash_flow_statement"},
	{SourceFieldID: 564, FieldCode: "net_increase_in_funds_borrowed_from_other_financial_institutions", FieldNameCN: "向其他金融机构拆入资金净增加额(万元)", FieldNameEN: "Net Increase in Funds Borrowed from Other Financial Institutions", Category: "cash_flow_statement"},
	{SourceFieldID: 565, FieldCode: "cash_received_from_premiums_of_original_insurance_contracts", FieldNameCN: "收到原保险合同保费取得的现金(万元)", FieldNameEN: "Cash Received from Premiums of Original Insurance Contracts", Category: "cash_flow_statement"},
	{SourceFieldID: 566, FieldCode: "net_cash_received_from_reinsurance_business", FieldNameCN: "收到再保险业务现金净额(万元)", FieldNameEN: "Net Cash Received from Reinsurance Business", Category: "cash_flow_statement"},
	{SourceFieldID: 567, FieldCode: "net_increase_in_policyholder_deposits_and_investment_funds", FieldNameCN: "保户储金及投资款净增加额(万元)", FieldNameEN: "Net Increase in Policyholder Deposits and Investment Funds", Category: "cash_flow_statement"},
	{SourceFieldID: 568, FieldCode: "net_increase_in_proceeds_from_disposal_of_financial_assets_at_fair_value_through_profit_or_loss", FieldNameCN: "处置以公允价值计量且其变动计入当期损益的金融资产净增加额(万元)", FieldNameEN: "Net Increase in Proceeds from Disposal of Financial Assets at Fair Value through Profit or Loss", Category: "cash_flow_statement"},
	{SourceFieldID: 569, FieldCode: "cash_received_from_interest_fees_and_commissions", FieldNameCN: "收取利息、手续费及佣金的现金(万元)", FieldNameEN: "Cash Received from Interest, Fees and Commissions", Category: "cash_flow_statement"},
	{SourceFieldID: 570, FieldCode: "net_increase_in_funds_borrowed", FieldNameCN: "拆入资金净增加额(万元)", FieldNameEN: "Net Increase in Funds Borrowed", Category: "cash_flow_statement"},
	{SourceFieldID: 571, FieldCode: "net_increase_in_repurchase_business_funds", FieldNameCN: "回购业务资金净增加额(万元)", FieldNameEN: "Net Increase in Repurchase Business Funds", Category: "cash_flow_statement"},
	{SourceFieldID: 572, FieldCode: "net_increase_in_loans_and_advances_to_customers", FieldNameCN: "客户贷款及垫款净增加额(万元)", FieldNameEN: "Net Increase in Loans and Advances to Customers", Category: "cash_flow_statement"},
	{SourceFieldID: 573, FieldCode: "net_increase_in_deposits_with_central_bank_and_other_banks", FieldNameCN: "存放中央银行和同业款项净增加额(万元)", FieldNameEN: "Net Increase in Deposits with the Central Bank and Other Banks", Category: "cash_flow_statement"},
	{SourceFieldID: 574, FieldCode: "cash_paid_for_claims_under_original_insurance_contracts", FieldNameCN: "支付原保险合同赔付款项的现金(万元)", FieldNameEN: "Cash Paid for Claims under Original Insurance Contracts", Category: "cash_flow_statement"},
	{SourceFieldID: 575, FieldCode: "cash_paid_for_interest_fees_and_commissions", FieldNameCN: "支付利息、手续费及佣金的现金(万元)", FieldNameEN: "Cash Paid for Interest, Fees and Commissions", Category: "cash_flow_statement"},
	{SourceFieldID: 576, FieldCode: "cash_paid_for_policyholder_dividends", FieldNameCN: "支付保单红利的现金(万元)", FieldNameEN: "Cash Paid for Policyholder Dividends", Category: "cash_flow_statement"},
	{SourceFieldID: 577, FieldCode: "cash_received_by_subsidiaries_from_capital_contributions_by_non_controlling_interests", FieldNameCN: "其中:子公司吸收少数股东投资收到的现金(万元)", FieldNameEN: "Cash Received by Subsidiaries from Capital Contributions by Non-controlling Interests", Category: "cash_flow_statement"},
	{SourceFieldID: 578, FieldCode: "cash_paid_by_subsidiaries_for_dividends_and_profit_distribution_to_non_controlling_interests", FieldNameCN: "其中:子公司支付给少数股东的股利、利润(万元)", FieldNameEN: "Cash Paid by Subsidiaries for Dividends and Profit Distribution to Non-controlling Interests", Category: "cash_flow_statement"},
	{SourceFieldID: 579, FieldCode: "depreciation_and_amortization_of_investment_property", FieldNameCN: "投资性房地产的折旧及摊销(万元)", FieldNameEN: "Depreciation and Amortization of Investment Property", Category: "cash_flow_statement"},
	{SourceFieldID: 580, FieldCode: "credit_impairment_losses_for_cash_flow_reconciliation", FieldNameCN: "信用减值损失(万元)", FieldNameEN: "Credit Impairment Losses for Cash Flow Reconciliation", Category: "cash_flow_statement"},
}
